### PR TITLE
Update lock file

### PR DESCRIPTION
**Pull request by honza**
This is done by running "dep ensure".  Some of the digests were missing from the file.

### CODE REVIEW

**Comment by dhellmann** [comment]
When I run "go dep" after checking out this PR, it reverts the changes. :-/

I may need to sit down and pick your brain about go dependencies.

**Comment by honza** [comment]
:disappointed: I give up. I clearly don't know how this works either.

What version of dep are you using? Mine is 0.5.0.

**Comment by honza** [comment]
After checking out this PR, and with a clean working directory, what does `dep check` say? What about `dep status`?

**Comment by dhellmann** [comment]
`dep version` tells me

```
dep:
 version     : devel
 build date  :
 git hash    :
 go version  : go1.11beta2
 go compiler : gc
 platform    : linux/amd64
```

I installed the package on Fedora 29. Maybe that's my mistake, and I should be installing it some other way?

**Comment by dhellmann** [comment]
`yum info dep` give

```
Name         : dep
Version      : 0.4.1
Release      : 4.fc29
Arch         : x86_64
Size         : 15 M
Source       : dep-0.4.1-4.fc29.src.rpm
Repo         : @System
From repo    : fedora
Summary      : Go dependency management tool
URL          : https://github.com/golang/dep
License      : BSD
Description  : Go dependency management tool
```

**Comment by dhellmann** [comment]
`dep check` isn't a known command. Maybe that's new to 0.5.0.

`dep status` says

```
Lock inputs-digest mismatch. This happens when Gopkg.toml is modified.
Run `dep ensure` to regenerate the inputs-digest.
input-digest mismatch
```

Running `dep ensure` and then `dep status` gives

```
PROJECT                                             CONSTRAINT          VERSION        REVISION  LATEST   PKGS USED
cloud.google.com/go                                 v0.35.1             v0.35.1        28a4bc8   v0.35.1  1
github.com/BurntSushi/toml                          v0.3.1              v0.3.1         3012a1d   v0.3.1   1
github.com/PuerkitoBio/purell                       v1.1.0              v1.1.0         0bcb03f   v1.1.0   1
github.com/PuerkitoBio/urlesc                       branch master       branch master  de5bf2a   de5bf2a  1
github.com/beorn7/perks                             branch master       branch master  3a771d9   3a771d9  1
github.com/davecgh/go-spew                          v1.1.1              v1.1.1         8991bc2   v1.1.1   1
github.com/emicklei/go-restful                      v2.8.1              v2.8.1         e37671a   v2.8.1   2
github.com/ghodss/yaml                              v1.0.0              v1.0.0         0ca9ea5   v1.0.0   1
github.com/go-logr/logr                             branch master       branch master  9fb12b3   9fb12b3  1
github.com/go-logr/zapr                             v0.1.0              v0.1.0         7536572   v0.1.0   1
github.com/go-openapi/jsonpointer                   v0.18.0             v0.18.0        ef5f0af   v0.18.0  1
github.com/go-openapi/jsonreference                 v0.18.0             v0.18.0        8483a88   v0.18.0  1
github.com/go-openapi/spec                          v0.18.0             v0.18.0        5b6cdde   v0.18.0  1
github.com/go-openapi/swag                          v0.18.0             v0.18.0        1d29f06   v0.18.0  1
github.com/gobuffalo/envy                           v1.6.13             v1.6.13        d06f4c3   v1.6.13  1
github.com/gogo/protobuf                            v1.2.0              v1.2.0         4cbf7e3   v1.2.0   2
github.com/golang/glog                              branch master       branch master  23def4e   23def4e  1
github.com/golang/groupcache                        branch master       branch master  c65c006   5b532d6  1
github.com/golang/protobuf                          v1.2.0              v1.2.0         aa810b6   v1.2.0   5
github.com/google/btree                             branch master       branch master  4030bb1   4030bb1  1
github.com/google/gofuzz                            branch master       branch master  24818f7   24818f7  1
github.com/google/uuid                              v1.1.0              v1.1.0         9b3b1e0   v1.1.0   1
github.com/googleapis/gnostic                       v0.2.0              v0.2.0         7c66326   v0.2.0   3
github.com/gregjones/httpcache                      branch master       branch master  c63ab54   3befbb6  2
github.com/hashicorp/golang-lru                     v0.5.0              v0.5.0         20f1fb7   v0.5.0   2
github.com/imdario/mergo                            v0.3.6              v0.3.6         9f23e2d   v0.3.6   1
github.com/joho/godotenv                            v1.3.0              v1.3.0         23d116a   v1.3.0   1
github.com/json-iterator/go                         v1.1.5              v1.1.5         1624edc   v1.1.5   1
github.com/konsorten/go-windows-terminal-sequences  v1.0.1              v1.0.1         5c8c8bd   v1.0.1   1
github.com/mailru/easyjson                          branch master       branch master  60711f1   6243d8e  3
github.com/markbates/inflect                        v1.0.4              v1.0.4         24b8319   v1.0.4   1
github.com/mattbaird/jsonpatch                      branch master       branch master  81af803   81af803  1
github.com/matttproud/golang_protobuf_extensions    v1.0.1              v1.0.1         c12348c   v1.0.1   1
github.com/modern-go/concurrent                     1.0.3               1.0.3          bacd9c7   1.0.3    1
github.com/modern-go/reflect2                       1.0.1               1.0.1          4b7aa43   1.0.1    1
github.com/operator-framework/operator-sdk          branch master       branch master  16ba990   a882a84  9
github.com/pborman/uuid                             v1.2                v1.2           adf5a74   v1.2     1
github.com/petar/GoLLRB                             branch master       branch master  53be0d3   53be0d3  1
github.com/peterbourgon/diskv                       v2.0.1              v2.0.1         5f041e8   v2.0.1   1
github.com/prometheus/client_golang                 v0.9.2              v0.9.2         505eaef   v0.9.2   3
github.com/prometheus/client_model                  branch master       branch master  5672610   fd36f42  1
github.com/prometheus/common                        branch master       branch master  2998b13   7a3416f  3
github.com/prometheus/procfs                        branch master       branch master  bf6a532   e4d4a22  4
github.com/rogpeppe/go-internal                     v1.1.0              v1.1.0         68d1cb0   v1.1.0   3
github.com/sirupsen/logrus                          v1.3.0              v1.3.0         e1e72e9   v1.3.0   1
github.com/spf13/afero                              v1.2.1              v1.2.1         f4711e4   v1.2.1   2
github.com/spf13/pflag                              v1.0.3              v1.0.3         298182f   v1.0.3   1
go.uber.org/atomic                                  v1.3.2              v1.3.2         1ea20fb   v1.3.2   1
go.uber.org/multierr                                v1.1.0              v1.1.0         3c49374   v1.1.0   1
go.uber.org/zap                                     v1.9.1              v1.9.1         ff33455   v1.9.1   6
golang.org/x/crypto                                 branch master       branch master  6407268   a4c6cb3  1
golang.org/x/net                                    branch master       branch master  ed066c8   3a22650  6
golang.org/x/oauth2                                 branch master       branch master  5dab416   9b3c759  5
golang.org/x/sys                                    branch master       branch master  054c452   ec7b60b  2
golang.org/x/text                                   v0.3.0              v0.3.0         f21a4df   v0.3.0   15
golang.org/x/time                                   branch master       branch master  85acf8d   85acf8d  1
golang.org/x/tools                                  branch master       branch master  9c309ee   83362c3  12
google.golang.org/appengine                         v1.4.0              v1.4.0         e9657d8   v1.4.0   10
gopkg.in/inf.v0                                     v0.9.1              v0.9.1         d2d2541   v0.9.1   1
gopkg.in/yaml.v2                                    v2.2.2              v2.2.2         51d6538   v2.2.2   1
k8s.io/api                                          b503174 (override)                 b503174            32
k8s.io/apiextensions-apiserver                      0cd23eb (override)                 0cd23eb            3
k8s.io/apimachinery                                 eddba98 (override)                 eddba98            43
k8s.io/client-go                                    d082d59 (override)                 d082d59            68
k8s.io/code-generator                               3dcf91f (override)                 3dcf91f            24
k8s.io/gengo                                        branch master       branch master  f8a0810   0689ccc  8
k8s.io/klog                                         v0.1.0              v0.1.0         a5bc97f   v0.1.0   1
k8s.io/kube-openapi                                 branch master       branch master  ced9eb3   ea82251  6
sigs.k8s.io/controller-runtime                      v0.1.8 (override)   v0.1.8         c63ebda   v0.1.8   28
```

**Comment by dhellmann** [comment]
Of course it also modifies the Gopkg.lock file.

**Comment by dhellmann** [comment]
I suspect we need to standardize on versions of go tools to fix this. I don't know what's standard for that. With python I would tell everyone to install from source. Maybe that's the right approach for golang, too?

**Comment by honza** [comment]
I installed mine via the curl [method](https://golang.github.io/dep/docs/installation.html#binary-installation) in the official documentation. According [to the release page](https://github.com/golang/dep/releases), `0.5.0` is currently the latest release.

I think if you have the latest stable of go itself, then most other things are available via `go get`.

**Comment by dhellmann** [comment]
OK, installing the latest version gives me the same behavior. This raises the question of which versions of the tools we need to be using to be compatible with whatever we usually use to package things for distribution, but we'll cross that bridge when we get to it.

**Pull request merged**
