### PR TITLE
Unvendor apimachinery

### PR DESCRIPTION
**Pull request by honza**
The types provided by k8s.io/apimachinery must work as a shared
dependency between servers and clients.  As such, the package cannot be
vendor.  When vendored, new instanced of `BareMetalHost` and similar
cannot be properly constructed.

For example, the `BareMetalStatus` struct has a meta field `LastUpdated`
which is of type `*k8s.io/apimachinery/pkg/apis/meta/v1/Time`.  The
import path for the `Time` struct is different/wrong when the meta
package is vendored in this repo.

### CODE REVIEW

**Comment by dhellmann** [comment]
Without the vendored copy of the library, compiling the operator fails on my system. Is there some other way I'm supposed to be installing the dependency?

```
$ operator-sdk test local ./test/e2e --namespace operator-test --up-local --debug --no-setup --go-test-flags "-v"
INFO[0000] Testing operator locally.
# github.com/metalkube/baremetal-operator/test/e2e
package github.com/metalkube/baremetal-operator/test/e2e (test)
	imports github.com/metalkube/baremetal-operator/pkg/apis
	imports github.com/metalkube/baremetal-operator/pkg/apis/metalkube/v1alpha1
	imports k8s.io/api/core/v1
	imports k8s.io/apimachinery/pkg/api/resource: cannot find package "k8s.io/apimachinery/pkg/api/resource" in any of:
	/home/stack/go/src/github.com/metalkube/baremetal-operator/vendor/k8s.io/apimachinery/pkg/api/resource (vendor tree)
	/usr/lib/golang/src/k8s.io/apimachinery/pkg/api/resource (from $GOROOT)
	/home/stack/go/src/k8s.io/apimachinery/pkg/api/resource (from $GOPATH)
FAIL	github.com/metalkube/baremetal-operator/test/e2e [setup failed]
```

**Comment by honza** [comment]
Try this:

```
$ cd $GOPATH/src/github.com/metalkube/baremetal-operator
$ go get ./...
```

**Comment by honza** [comment]
The more I think about this, the more I realize this is the wrong solution. Sorry for the noise.

**Comment by dhellmann** [comment]
No worries. I'm still pretty confused about dependency management under go myself, so if you have ideas about how best to set this up I'm all ears.

**Pull request closed without merging**
